_meta:
  version: '1.0'
  entity_type: menu_link_content
  uuid: d7f4f1b2-af94-46b8-ac63-a8a5b14fb0f5
  bundle: menu_link_content
  default_langcode: en
default:
  enabled:
    -
      value: false
  title:
    -
      value: 'My privacy settings'
  menu_name:
    -
      value: footer
  link:
    -
      uri: 'internal:#'
      title: ''
      options:
        attributes:
          rel: open-consent-manager
  external:
    -
      value: false
  rediscover:
    -
      value: true
  weight:
    -
      value: 0
  expanded:
    -
      value: false
  revision_translation_affected:
    -
      value: true
