name: Basic SEO
description: Provides basic SEO best practices.
type: Drupal CMS
recipes:
  - core/recipes/content_editor_role
install:
  - easy_breadcrumb
  - node
  - pathauto
  - redirect
  - redirect_404
  - token
  - user
  - views
config:
  strict:
    # For safety's sake, only treat our bundled configuration strictly.
    - pathauto.pattern.menu_path
  import:
    redirect:
      - system.action.redirect_delete_action
    redirect_404: '*'
  actions:
    easy_breadcrumb.settings:
      simpleConfigUpdate:
        # Don't add current page in admin UI.
        applies_admin_routes: false
        # Add Schema.org Breadcrumb markup.
        add_structured_data_json_ld: true
        # Remove breadcrumbs when only home appears.
        # Since we print the page title in the crumb, this is only applies to the home page.
        hide_single_home_item: true
        # Don't alter the capitalization of breadcrumbs.
        capitalizator_mode: none
    redirect_404.settings:
      simpleConfigUpdate:
        suppress_404: true
    system.performance:
      simpleConfigUpdate:
        # Ensure caching is on and set to 15 minutes for Lighthouse.
        cache.page.max_age: 900
        # Ensure CSS and JS are preprocessed.
        css.preprocess: true
        js.preprocess: true
    user.role.content_editor:
      # Allow access to the redirect views.
      grantPermission: 'administer redirects'
