status: true
dependencies:
  config:
    - search_api.server.database
    - core.entity_view_mode.node.search_index
  module:
    - node
    - search_api
    - search_api_exclude
id: content
name: 'Content'
description: 'Can search within all content types.'
read_only: false
field_settings:
  rendered_item:
    label: 'Rendered HTML output'
    property_path: rendered_item
    type: text
    configuration:
      roles:
        - anonymous
      view_mode:
        'entity:node':
          ':default': search_index
  title:
    label: Title
    datasource_id: 'entity:node'
    property_path: title
    type: text
    boost: 3.0
    dependencies:
      module:
        - node
  type:
    label: 'Content type'
    datasource_id: 'entity:node'
    property_path: type
    type: string
    dependencies:
      module:
        - node
datasource_settings:
  'entity:node':
    bundles:
      default: true
      selected: { }
    languages:
      default: true
      selected: { }
processor_settings:
  add_url: { }
  aggregated_field: { }
  custom_value: { }
  entity_status: { }
  entity_type: { }
  highlight:
    weights:
      postprocess_query: 0
    prefix: '<strong>'
    suffix: '</strong>'
    excerpt: true
    excerpt_always: false
    excerpt_length: 256
    exclude_fields: { }
    highlight: always
    highlight_partial: true
  html_filter:
    weights:
      preprocess_index: -15
      preprocess_query: -15
    all_fields: false
    fields:
      - rendered_item
      - title
      - type
    title: true
    alt: true
    tags:
      b: 2
      h1: 5
      h2: 3
      h3: 2
      strong: 2
  ignorecase:
    weights:
      preprocess_index: -20
      preprocess_query: -20
    all_fields: false
    fields:
      - rendered_item
      - title
      - type
  language_with_fallback: { }
  node_exclude: { }
  rendered_item: { }
  reverse_entity_references: { }
  stemmer:
    weights:
      preprocess_index: 0
      preprocess_query: 0
    all_fields: false
    fields:
      - rendered_item
      - title
    exceptions:
      mexican: mexic
      texan: texa
  tokenizer:
    weights:
      preprocess_index: -6
      preprocess_query: -6
    all_fields: false
    fields:
      - rendered_item
      - title
    spaces: ''
    ignored: ._-
    overlap_cjk: 1
    minimum_word_size: '3'
tracker_settings:
  default:
    indexing_order: lifo
options:
  cron_limit: 10
  index_directly: true
  track_changes_in_references: true
server: database
