status: true
dependencies:
  config:
    - search_api.index.content
    - views.view.search
  module:
    - views
    - search_api_autocomplete
id: content_autocomplete
label: Content Autocomplete
index_id: content
suggester_settings:
  live_results:
    fields: { }
    highlight:
      enabled: false
      field: ''
    suggest_keys: false
    view_modes: {  }
suggester_weights:
  live_results: 0
suggester_limits: { }
search_settings:
  'views:search':
    displays:
      default: true
      selected: { }
options:
  limit: 10
  min_length: 1
  show_count: false
  delay: null
  submit_button_selector: ':submit'
  autosubmit: true
