name: 'Easy Email: Default Template'
description: 'A default Easy Email template configured to override all emails sent from the site.'
type: 'Easy Email'
recipes:
  - easy_email_text_format
install:
  - easy_email
  - easy_email_override
config:
  import:
    easy_email: "*"
    easy_email_override: "*"
