name: 'Easy Email: Express Mail'
description: 'Easy Email configuration that replaces all core emails with HTML formatted emails.'
type: 'Easy Email'
recipes:
  - easy_email_standard
  - easy_email_types_core
  - easy_email_types_default
